// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yvP5sP-E-L6fHd2Arppg2lDPYFSthF4',
    appId: '1:407560381907:web:28cbe4e2b11ba0e5ab3b26',
    messagingSenderId: '407560381907',
    projectId: 'testproj-dbcbd',
    authDomain: 'testproj-dbcbd.firebaseapp.com',
    storageBucket: 'testproj-dbcbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSkTlsg_jbMYmZcOt2fktGWco2Ei4zrQo',
    appId: '1:566517432772:android:b6b0b52c56819a55206491',
    messagingSenderId: '566517432772',
    projectId: 'vevij-16299',
    storageBucket: 'vevij-16299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAguo5LdpmxeXfcrevCKDGpKzz2zOOYRMg',
    appId: '1:407560381907:ios:74def6166f129911ab3b26',
    messagingSenderId: '407560381907',
    projectId: 'testproj-dbcbd',
    storageBucket: 'testproj-dbcbd.firebasestorage.app',
    androidClientId: '407560381907-28orr6n9ifs38uoe6o2dvbg0gh5alcvk.apps.googleusercontent.com',
    iosClientId: '407560381907-6bleespoanh5jjragb5mtm97qa19lpcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vevij',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAguo5LdpmxeXfcrevCKDGpKzz2zOOYRMg',
    appId: '1:407560381907:ios:74def6166f129911ab3b26',
    messagingSenderId: '407560381907',
    projectId: 'testproj-dbcbd',
    storageBucket: 'testproj-dbcbd.firebasestorage.app',
    androidClientId: '407560381907-28orr6n9ifs38uoe6o2dvbg0gh5alcvk.apps.googleusercontent.com',
    iosClientId: '407560381907-6bleespoanh5jjragb5mtm97qa19lpcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vevij',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoFrLWpQTUrHw-wjOb3_lp5PTyDsxb7nw',
    appId: '1:566517432772:web:59e2de07ec99d02f206491',
    messagingSenderId: '566517432772',
    projectId: 'vevij-16299',
    authDomain: 'vevij-16299.firebaseapp.com',
    storageBucket: 'vevij-16299.firebasestorage.app',
    measurementId: 'G-CZNNL7816B',
  );

}